language: python

python:
  - 3.6.2

install:
  - pip install -r requirements.txt

before_script:
- psql -c 'create database the7chefs;' -U postgres
- psql -c "CREATE USER the7chefsapp WITH PASSWORD 'qwe123qwe123';" -U postgres
- psql -c 'CREATE DATABASE the7chefs OWNER the7chefsapp;' -U postgres
- psql -c 'ALTER ROLE the7chefsapp superuser;' -U postgres
- psql -c 'GRANT ALL PRIVILEGES ON DATABASE the7chefs TO the7chefsapp;' -U postgres
- python manage.py migrate

# ALTER ROLE the7chefsapp SET client_encoding TO 'utf8';
# ALTER ROLE the7chefsapp SET default_transaction_isolation TO 'read committed';
# ALTER ROLE the7chefsapp SET timezone TO 'UTC';


script: python manage.py test

services:
  - postgresql

postgres:
  adapter: postgresql
  database: the7chefs
  username: the7chefsapp
  password: qwe123qwe123
