# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-05 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevchefs_api', '0002_auto_20170905_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecomment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='sevchefs_api.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecipeComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipeinstruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Instruction', to='sevchefs_api.Recipe'),
        ),
    ]
