# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-05 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevchefs_api', '0003_auto_20170905_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_required',
            field=models.DurationField(null=True),
        ),
    ]
