# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-05 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevchefs_api', '0004_auto_20170905_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='upload_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sevchefs_api.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipeinstruction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='sevchefs_api.Recipe'),
        ),
    ]
