# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-07 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevchefs_api', '0005_auto_20170905_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTagTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ingredient_image_directory_path'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_image_directory_path'),
        ),
        migrations.AlterField(
            model_name='recipeinstruction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_instruction_image_directory_path'),
        ),
        migrations.AddField(
            model_name='recipetagtable',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevchefs_api.Recipe'),
        ),
        migrations.AddField(
            model_name='recipetagtable',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevchefs_api.RecipeTag'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(through='sevchefs_api.RecipeTagTable', to='sevchefs_api.RecipeTag'),
        ),
    ]
