# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevchefs_api', '0006_auto_20170907_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetag',
            name='text',
            field=models.TextField(unique=True),
        ),
    ]
