# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-08 10:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sevchefs_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('sevchefs_api', '0007_auto_20170907_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='sevchefs_api.UserProfile'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sevchefs_api.models.ingredient_image_directory_path),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sevchefs_api.models.recipe_image_directory_path),
        ),
        migrations.AlterField(
            model_name='recipeinstruction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sevchefs_api.models.recipe_instruction_image_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=sevchefs_api.models.user_avatar_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
