# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-21 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevchefs_api', '0008_auto_20171008_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time_required',
        ),
        migrations.AddField(
            model_name='recipeinstruction',
            name='time_required',
            field=models.DurationField(null=True),
        ),
    ]
