# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-01 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sevchefs_api', '0011_activitytimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytimeline',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_timeline', to=settings.AUTH_USER_MODEL),
        ),
    ]
